import {useState} from 'react';
const number=(value:any)=>Number.isFinite(Number(value))?new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(Number(value)):'—';
const percent=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'—';
export function GameStats({stats,setStats,load,close}:{stats:any;setStats:(value:any)=>void;load:(partition:string|undefined,method:string)=>Promise<any>;close:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),summary=stats.summary?.[0]??{},life=stats.lifecycle??{},engagement=stats.engagement??{},peak=Math.max(1,...(stats.distribution??[]).map((b:any)=>b.count));
  const change=async(partition:string|undefined,method:string)=>{setBusy(true);setError('');try{setStats({...stats,...await load(partition,method)});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="modal-backdrop" onClick={close}><section className="stats-modal" role="dialog" aria-modal="true" aria-label="Game statistics" onClick={e=>e.stopPropagation()}>
    <button className="close" aria-label="Close statistics" onClick={close}>×</button><div className="eyebrow">A LITTLE BRAGGING</div><h2>{stats.title}</h2>
    <div className="stats-filters">{!!stats.partitions?.length&&<label>Compare like for like<select aria-label="Score group" disabled={busy} value={stats.partition} onChange={e=>void change(e.target.value,stats.method??'all')}>{stats.partitions.map((p:any,i:number)=><option key={p.key} value={p.key}>{p.dimensions?`${p.dimensions.players} players · ${['Mellow','Normal','Spicy','Wild'][p.dimensions.difficulty]} · ${p.dimensions.mode} · ${p.dimensions.controllers.join(' + ')}`:`Saved rules group ${i+1}`} ({p.plays})</option>)}</select></label>}
      <label>Recorded controls<select aria-label="Recorded controls" value={stats.method??'all'} disabled={busy} onChange={e=>void change(stats.partition,e.target.value)}><option value="all">All controls</option><option value="keyboard">Keyboard</option><option value="virtual-pad">Virtual pad</option><option value="mixed">Keyboard + virtual pad</option><option value="none">No input recorded</option></select></label>
    </div>
    <div className="stat-cards"><div><strong>{summary.plays??0}</strong><span>Recorded scores</span></div><div><strong>{percent(summary.successes,summary.plays)}</strong><span>Met the game’s objective</span></div><div><strong>{summary.plays?number(summary.median_score):'—'}</strong><span>Median score</span></div></div>
    {!!summary.plays&&<><h3>How the scores spread out</h3><p className="stats-note">All attempts in this score group and control filter. The leaderboard below keeps each player’s best.</p><ol className="score-distribution" aria-label="Score distribution">{stats.distribution.map((bin:any)=><li key={bin.bucket}><span>{number(bin.low)}{bin.low!==bin.high?`–${number(bin.high)}`:''}</span><div><i style={{width:`${bin.count/peak*100}%`}}/></div><strong>{bin.count}</strong></li>)}</ol></>}
    <h3>Best scores</h3>{stats.leaders?.slice(0,8).map((l:any,i:number)=><div className="leader" key={i}><strong>{l.record.name}</strong><span>{number(l.score)}</span><small>{l.record.controllers?.join(' + ')}</small></div>)}{!stats.leaders?.length&&<p>No scores in this group yet.</p>}
    <details className="party-statistics"><summary>Round completion and repeat play</summary><p className="stats-note">This version across all settings and controls. Counts begin with tracked rounds; older score records are excluded.</p>
      <div className="stat-cards"><div><strong>{percent(life.completed,life.tracked-life.active)}</strong><span>Rounds finished normally</span></div><div><strong>{percent(engagement.rematched_parties,engagement.completed_parties)}</strong><span>Finished parties rematched</span></div></div>
      <p>{life.completed??0} completed · {life.interrupted??0} interrupted · {life.abandoned??0} abandoned · {life.technical_failures??0} technical failures · {life.active??0} in progress</p>
      <p className="stats-note">A finished round may be a win or a loss. Rematches include fresh-seed attempts started from results. {life.tracked_since&&`Tracking since ${new Date(life.tracked_since).toLocaleDateString()}.`}</p>
    </details>{error&&<p role="alert">{error}</p>}
  </section></div>;
}
