import {Store} from './store';
export type InputMethod='all'|'keyboard'|'virtual-pad'|'mixed'|'none';
const methodSql="CASE WHEN record->'inputMethods' @> '[\"keyboard\",\"virtual-pad\"]'::jsonb THEN 'mixed' WHEN record->'inputMethods' @> '[\"keyboard\"]'::jsonb THEN 'keyboard' WHEN record->'inputMethods' @> '[\"virtual-pad\"]'::jsonb THEN 'virtual-pad' ELSE 'none' END";
export async function gameStats(store:Store,versionId:string,partition?:string,method:InputMethod='all'){
 const version=await store.version(versionId),order=version.manifest.meta.score.order==='lower'?'ASC':'DESC';
 const partitions=await store.query("SELECT partition_key AS key,record->'dimensions' AS dimensions,count(*)::int AS plays FROM results WHERE version_id=$1 GROUP BY partition_key,record->'dimensions' ORDER BY plays DESC,partition_key",[versionId]);
 const selected=partition??partitions[0]?.key;if(selected&&!partitions.some(p=>p.key===selected))throw new Error('Score group not found');
 const params=[versionId,selected??'',method],where=`version_id=$1 AND partition_key=$2 AND ($3='all' OR (${methodSql})=$3)`;
 const [leaders,summary,distribution,lifecycle,engagement]=await Promise.all([
  store.query(`SELECT * FROM (SELECT DISTINCT ON (coalesce(guest_id,record->>'playerId')) record,score,partition_key FROM results WHERE ${where} ORDER BY coalesce(guest_id,record->>'playerId'),score ${order}) best ORDER BY score ${order} LIMIT 20`,params),
  store.query(`SELECT count(*)::int AS plays,avg(score) AS average_score,min(score) AS minimum_score,max(score) AS maximum_score,percentile_cont(0.5) WITHIN GROUP (ORDER BY score) AS median_score,count(*) FILTER (WHERE record->>'outcome'='success')::int AS successes,count(*) FILTER (WHERE record->>'outcome'='failure')::int AS failures FROM results WHERE ${where}`,params),
  store.query(`WITH scores AS (SELECT score FROM results WHERE ${where}), bounds AS (SELECT min(score) AS low,max(score) AS high FROM scores), buckets AS (SELECT score,low,high,CASE WHEN low=high THEN 0 ELSE least(5,floor((score-low)/(high-low)*6)::int) END AS bucket FROM scores CROSS JOIN bounds) SELECT bucket,count(*)::int AS count,min(low)+(max(high)-min(low))*bucket/6 AS low,min(low)+(max(high)-min(low))*(bucket+1)/6 AS high FROM buckets GROUP BY bucket ORDER BY bucket`,params),
  store.query("SELECT count(*)::int AS tracked,count(*) FILTER (WHERE a.status='complete')::int AS completed,count(*) FILTER (WHERE a.status IN ('preparing','playing'))::int AS active,count(*) FILTER (WHERE a.status='interrupted')::int AS interrupted,count(*) FILTER (WHERE a.status='aborted' AND m.record->'termination'->>'kind'='abandoned')::int AS abandoned,count(*) FILTER (WHERE a.status='aborted' AND coalesce(m.record->'termination'->>'kind','technical')='technical')::int AS technical_failures,min(a.prepared_at) AS tracked_since FROM round_attempts a JOIN matches m ON m.id=a.match_id WHERE a.version_id=$1",[versionId]),
  store.query("SELECT count(DISTINCT a.match_id)::int AS completed_parties,count(DISTINCT a.match_id) FILTER (WHERE EXISTS(SELECT 1 FROM replay_plays r WHERE r.match_id=a.match_id))::int AS replayed_parties,count(DISTINCT a.match_id) FILTER (WHERE EXISTS(SELECT 1 FROM matches n WHERE n.record->>'rematchOf'=a.match_id))::int AS rematched_parties FROM round_attempts a JOIN matches m ON m.id=a.match_id WHERE a.version_id=$1 AND m.status='complete'",[versionId])
 ]);
 return {partitions,partition:selected,method,leaders,summary,distribution,lifecycle:lifecycle[0],engagement:engagement[0]};
}
export async function creationStats(store:Store,ownerId:string){
 const [stats]=await store.query("SELECT count(*)::int AS total,count(*) FILTER (WHERE status='ready')::int AS ready,count(*) FILTER (WHERE status='failed')::int AS failed,count(*) FILTER (WHERE status='working')::int AS working,coalesce(sum(greatest(jsonb_array_length(coalesce(record->'attempts','[]'::jsonb))-1,0)),0)::int AS code_repairs,count(*) FILTER (WHERE jsonb_array_length(coalesce(record->'attempts','[]'::jsonb))>1)::int AS repaired_jobs,coalesce(sum(greatest(jsonb_array_length(coalesce(record->'musicAttempts','[]'::jsonb))-1,0)),0)::int AS music_repairs FROM jobs WHERE owner_id=$1",[ownerId]);return stats;
}
