/** Offline only: stop the app before opening its PGlite store. */
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {Store} from '../server/store';import {Sandbox} from '../runtime/sandbox';import {ReplayRunner} from '../runtime/replay';
const store=new Store();await store.init();
try{
  const [row]=await store.query('SELECT record FROM jobs WHERE id=$1',['bf0f76b4d0ebda5811090a5f']),job=row.record;
  const [failed]=await store.query('SELECT record FROM jobs WHERE id=$1',['30317daa841211a615aeb77d']);
  assert.equal(failed.record.branches.music,'failed');assert.equal(job.status,'ready');assert.equal(job.musicOnly,true);assert.equal(job.branches.code,'reused');assert.equal(job.branches.art,'reused');assert.equal(job.branches.music,'ready');
  const original=await store.version(job.remix),finished=await store.version(job.finishedVersion);
  assert.equal(job.remix,failed.record.previewVersion);assert.equal(finished.source,original.source);assert.equal(finished.code,original.code);assert.equal(await store.runtime(finished),await store.runtime(original));assert.deepEqual(finished.manifest.assets,original.manifest.assets);assert.deepEqual(finished.manifest.meta,original.manifest.meta);assert.ok(finished.manifest.music);assert.equal(finished.manifest.provenance.draft,false);
  const [first]=await store.query('SELECT * FROM matches WHERE id=$1',['c106339029aeb848aa2b1a34']),[second]=await store.query('SELECT * FROM matches WHERE id=$1',['8b480dd520488ee0a06b5133']);
  assert.equal(first.status,'complete');assert.equal(second.status,'complete');assert.equal(first.record.rounds[1].versionId,finished.id);assert.equal(first.record.settings.targetPlayers,3);assert.equal(second.record.settings.targetPlayers,2);
  const [before]=await store.query('SELECT * FROM challenges WHERE id=$1',[first.challenge_id]),[after]=await store.query('SELECT * FROM challenges WHERE id=$1',[second.challenge_id]);
  assert.notEqual(before.id,after.id);assert.deepEqual(before.definition.versions,first.record.rounds.map((r:any)=>r.versionId));assert.deepEqual(after.definition.versions,second.record.rounds.map((r:any)=>r.versionId));assert.equal(before.definition.versions.length,2);assert.equal(after.definition.versions.length,1);assert.equal(before.definition.settings.seed,after.definition.settings.seed);
  assert.deepEqual(before.definition.settings.botTypes,['scripted','jev','jev']);assert.deepEqual(after.definition.settings.botTypes,['scripted','jev']);
  assert.equal(before.definition.selection.constraints.controls,'directions');assert.equal(before.definition.selection.constraints.maxDuration,15);assert.deepEqual(before.definition.selection.constraints.tags,['catch']);assert.equal(before.definition.selection.party.targetPlayers,2);
  const observer=JSON.parse(await readFile('evidence/party/observer-5ad355d7.json','utf8')),creating=observer.events.filter((e:any)=>e.creating===true);assert.ok(creating.length>0);assert.ok(creating.every((e:any)=>e.seats.filter((s:any)=>s.connected).length===2));
  const replays=[];for(const match of [first,second])for(const round of match.record.rounds){const version=await store.version(round.versionId),vm=await Sandbox.create(version.code,await store.runtime(version));try{const replay=new ReplayRunner(vm,round);replay.seek(round.status.tick);assert.equal(replay.verify(),true);replays.push({matchId:match.id,game:version.manifest.meta.title,exactReplay:true,records:round.records.map((r:any)=>({name:r.name,score:r.score,outcome:r.outcome,controllers:r.controllers,providerCalls:r.metrics.filter((m:any)=>m.started).length,models:[...new Set(r.metrics.map((m:any)=>m.model).filter(Boolean))]}))});}finally{vm.dispose();}}
  for(const round of first.record.rounds){for(const player of round.records.slice(0,2))assert.equal(player.metrics.length,0);assert.ok(round.records[2].metrics.some((m:any)=>m.model?.startsWith('jev-')));}
  const report={at:new Date().toISOString(),method:'Saved provider/job/challenge records and deterministic replay verification, combined with UI observations and a separate local WebSocket peer. No audible-quality, multitouch or genuine-human-session claim.',roomId:'5ad355d7',jobId:job.id,sourceVersion:original.id,finishedVersion:finished.id,models:job.models,previewMs:job.timings.previewMs,totalMs:job.timings.totalMs,runtimeIdentifiers:{before:original.manifest.runtimeVersion,after:finished.manifest.runtimeVersion},preserved:{source:true,compiledCode:true,runtimeBytes:true,artwork:true,metadata:true},twoConnectionsDuringCreation:true,originalChallenge:before.id,editedChallenge:after.id,selection:before.definition.selection,replays};
  await mkdir('evidence/party',{recursive:true});await writeFile('evidence/party/flow-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await store.close();}
