/** Abrupt-stop test against an isolated data directory and local production server. No UI or provider calls. */
import {spawn,type ChildProcess} from 'node:child_process';import {createServer} from 'node:net';import {once} from 'node:events';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WebSocket} from 'ws';import assert from 'node:assert/strict';import {Sandbox} from '../runtime/sandbox';import {ReplayRunner} from '../runtime/replay';
const root=await mkdtemp(join(tmpdir(),'microfinity-restart-')),probe=createServer();await new Promise<void>(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=(probe.address() as {port:number}).port;await new Promise<void>(resolve=>probe.close(()=>resolve()));
const base=`http://127.0.0.1:${port}`;let child:ChildProcess|undefined;const sockets:WebSocket[]=[];
async function until(check:()=>boolean,timeout=20000){const end=performance.now()+timeout;while(!check()){if(performance.now()>end)throw new Error('Restart check timed out');await new Promise(r=>setTimeout(r,30));}}
async function boot(){let ready=false,log='';child=spawn(process.execPath,['dist/server/index.js'],{env:{...process.env,PORT:String(port),NODE_ENV:'production',DATA_DIR:root,DATABASE_URL:'',OPENAI_API_KEY:'',TYPESAFE_API_KEY:'',DOTENV_CONFIG_PATH:join(root,'no-provider.env')},stdio:['ignore','pipe','pipe']});child.stdout?.on('data',b=>{log=(log+b).slice(-4000);if(String(b).includes('Microfinity is ready:'))ready=true;});child.stderr?.on('data',b=>log=(log+b).slice(-4000));await until(()=>{if(child?.exitCode!==null)throw new Error('Test server exited: '+log);return ready;},30000);}
async function stop(signal:NodeJS.Signals){if(child&&child.exitCode===null&&child.signalCode===null){const exited=once(child,'exit');child.kill(signal);await exited;}}
async function api(path:string,token?:string,body?:unknown){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
function connect(roomId:string,guest:any){const ws=new WebSocket(base.replace('http','ws')+'/socket');sockets.push(ws);const c:any={ws,state:null,errors:[],loaded:''};c.send=(m:any)=>ws.send(JSON.stringify(m));ws.on('open',()=>c.send({type:'join',roomId,token:guest.token}));ws.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='clock-probe'){c.send({type:'clock-reply',id:m.id,clientTime:performance.now()});return;}if(m.type==='error')c.errors.push(m.message);if(m.type!=='state')return;c.state=m;if(m.phase==='lobby'&&!m.seats.find((s:any)=>s.id===m.playerId).ready)c.send({type:'ready'});if(m.phase==='preparing'&&c.loaded!==m.matchId){c.loaded=m.matchId;c.send({type:'loaded',versionId:m.manifest.id});}});return c;}
try{
 await boot();const library=await api('/library'),version=library.find((v:any)=>v.gameId==='toast-catch'),owner=await api('/guest',undefined,{name:'Challenge author'}),host=await api('/guest',undefined,{name:'New party host'}),friend=await api('/guest',undefined,{name:'New party friend'});
 const originalRoom=await api('/rooms',owner.token,{versions:[version.id],settings:{targetPlayers:2,botType:'scripted',difficulty:1}}),original=connect(originalRoom.id,owner);await until(()=>original.state?.phase==='lobby');original.send({type:'start'});await until(()=>original.state?.phase==='match-result');const firstMatch=original.state.matchId,challengeId=original.state.challengeId;await api(`/matches/${firstMatch}/replay`,owner.token,{});original.ws.close();
 const nextRoom=await api(`/challenges/${challengeId}/play`,host.token,{}),a=connect(nextRoom.id,host);await until(()=>a.state?.phase==='lobby');assert.equal(a.state.seats.length,2);const b=connect(nextRoom.id,friend);await until(()=>b.state?.phase==='lobby'&&a.state.seats.some((s:any)=>s.guestId===friend.id&&s.connected)&&a.state.seats.every((s:any)=>s.ready));assert.deepEqual(b.errors,[]);a.send({type:'start'});await until(()=>a.state?.phase==='playing'&&a.state.view?.time>6);
 const matchId=a.state.matchId,liveTime=a.state.view.time;assert.equal(a.state.challengeId,challengeId);await assert.rejects(()=>api('/matches/'+matchId,friend.token),/only to members/);await stop('SIGKILL');await boot();
 const recovered=await api('/matches/'+matchId,friend.token);assert.equal(recovered.status,'interrupted');assert.equal(recovered.record.termination.reason,'server-restart');assert.equal(recovered.record.rounds.length,0);assert.ok(recovered.record.activeRound.status.tick>0);assert.ok(recovered.record.activeRound.status.time<=liveTime);assert.ok(liveTime-recovered.record.activeRound.status.time<5.2);
 await assert.rejects(()=>api('/matches/'+matchId,owner.token),/only to members/);assert.ok((await api('/matches',friend.token)).some((m:any)=>m.id===matchId));assert.ok(!(await api('/matches',owner.token)).some((m:any)=>m.id===matchId));await api(`/matches/${matchId}/replay`,friend.token,{});await api(`/matches/${matchId}/replay`,friend.token,{});
 const storedVersion=await api('/versions/'+version.id),runtime=await fetch(base+storedVersion.manifest.runtimeUrl).then(r=>r.text()),vm=await Sandbox.create(storedVersion.code,runtime);try{const replay=new ReplayRunner(vm,recovered.record.activeRound);replay.seek(recovered.record.activeRound.status.tick);assert.equal(replay.verify(),true);}finally{vm.dispose();}
 const stats=await api('/stats/'+version.id);assert.equal(stats.lifecycle.completed,1);assert.equal(stats.lifecycle.interrupted,1);assert.equal(stats.lifecycle.tracked,2);assert.equal(stats.summary[0].plays,1);assert.equal(stats.engagement.replayed_parties,1);assert.deepEqual((await api('/challenges/'+challengeId)).definition.versions,[version.id]);
 const saved=await api('/matches/'+firstMatch,owner.token);assert.equal(saved.status,'complete');assert.equal(saved.record.rounds.length,1);
 const report={at:new Date().toISOString(),method:'Isolated production server using temporary PGlite, normal HTTP/WebSocket clients, deliberate SIGKILL during a live round, then restart. No browser, human-session or provider-call claim.',firstMatch,matchId,originalChallenge:challengeId,attemptChallenge:recovered.challenge_id,version:version.id,liveTime,lastCheckpointTime:recovered.record.activeRound.status.time,unsavedTailSeconds:liveTime-recovered.record.activeRound.status.time,replayExact:true,outsiderChallengeOwnerDenied:true,memberListingRetained:true,partialScoresAwarded:false,stats,recovered};
 await mkdir('evidence/recovery',{recursive:true});await writeFile('evidence/recovery/restart-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,matchId,liveTime,lastCheckpointTime:report.lastCheckpointTime,unsavedTailSeconds:report.unsavedTailSeconds,stats:stats.lifecycle}));
}finally{for(const ws of sockets)ws.close();await stop('SIGTERM');await rm(root,{recursive:true,force:true});}
